events {
  worker_connections 1024;
}

http {
  resolver 127.0.0.11 valid=30s ipv6=off;

  server {
    listen 80;
    server_name _;
    client_max_body_size 20M;

    location /api/auth/ {
      set $auth http://authentication-service:8000;
      proxy_pass $auth/api/auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/products/ {
      set $products http://product-service:8001;
      proxy_pass $products/api/products/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /health/auth {
      set $auth http://authentication-service:8000;
      proxy_pass $auth/health;
    }

    location /health/products {
      set $products http://product-service:8001;
      proxy_pass $products/health;
    }

    location / {
      set $frontend http://ecom:3000;
      proxy_pass $frontend;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_http_version 1.1;
    }
  }
}